flow_name = "项目开发指南"
flow_type = "SEQUENTIAL"
description =  '''
协助总结项目开发指南。主要包含：项目简介、软件特性、安装配置说明、使用说明、项目结构、参与开发指引。
'''

[[nodes]]
id = "node1"
name = "项目开发指南总结"
inputs = []
config = "node1_guide.toml"

