type = "Agent"
task = '''代码库概要分析'''

[manager]
max_turns = 5
mode = 'Questionnaire'
questions = [
    # "查询项目的目录结构，获知源文件位置，分析项目的构建方法(cmake or make)，编写clang-uml配置文件",
    # "调用generate_cpp_uml函数生成UML类图, 若出错，请修改配置文件后，重新生成",
    "查询项目的目录结构，获知源文件位置，分析项目的构建方法",
    "分析代码库的核心关键类(核心关键类指：类继承链的顶层或近顶层，频繁被其他类使用的类)",
]
participants = ["assistant"]
summary_prompt = '''
总结以上对话内容，汇总输出以下内容，内容尽可能详细，因为最后哦仅保存该总结部分，所有上述对话都会被遗忘:

1. 项目涉及的主要的类，详细描述它们之间的关系
- 类A是类B的父类，负责提供基本功能
- 类B继承自类A，扩展了类A的功能
- 类C依赖于类B，使用了类B的部分功能

2. 以json格式输出，输出最核心关键类，不要超过5个
例如：```json{"CoreClasses": ["namespace::class1", "namespace::class2"]}```

'''



[[agents]]
name = "assistant"
tools = ['read_file','run_command']
system_prompt =  '''
角色: 架构师
职责: 擅长代码库架构分析与总结


```


'''