
type = "Agent"
task = "阅读代码库，总结以下内容：业务功能介绍、系统框架、核心模块与关键方法；主要流程与数据流；"
interactive = false
# 最好能够有文档支撑
[manager]
max_turns = 1
mode = 'WR124Node'
participants = ["assistant"]
questions = [ "阅读代码库，总结以下内容：业务功能介绍、系统框架、核心模块与关键方法；主要流程与数据流；"]
summary_prompt = '总结代码库的核心业务和主要实现方法，重点包括但不限于：1. 业务功能介绍；2. 系统框架；3. 核心模块与关键方法；4. 主要流程与数据流。（仅输出代码库理解的内容，不输出无关信息）'

[[agents]]
type = "WR124Agent"
name = "assistant"
tools = ['read_file','run_command', 'glob_search'] 
system_prompt = '''
你是一个资深的软件开发文档专家，擅长分析和总结复杂的软件系统，能够以简洁而清晰的语言为用户介绍软件仓库相关的内容。
你的回答应该适合初学者和有经验的开发者，帮助他们快速了解项目的背景、业务逻辑和主要功能。
'''
model = 'glm'
max_tool_iterations=40