flow_name = "开发环境搭建"
flow_type = "SEQUENTIAL"
description =  '''
### 开发环境搭建
1. 编写项目构建指南
2. 依据构建指南构建开发环境

'''
[[nodes]]
id = "node1"
name = "构建指南编写"
inputs = []
config = "node1_guide.toml"


[[nodes]]
id = "node2"
name = "开发环境构建"
inputs = []
config = "node2_build.toml"


